### ISSUE TITLE
question about evaluation of SAP task

### ISSUE THREAD

**Issue by hkhpub** [seokhwankim/dstc5#2]
Hi, 
I am not quite sure about how is the unlabeled test data constructed.

I am working on only SAP task, so my question is
"For the SAP task, will the semantic tags and prev turn speech acts be provided in the test data?"

I cannot find any information about unlabeled test data in the handbook.

Thank you.

**Comment by seokhwankim** [comment]
As described in Section 5.3 in the handbook v3.0, you could convert the dataset into the format as the unlabeled testset that will be provided during the evaluation phase.

Please run 'convert_sap.py' and find the details from the generated 'sap.guide.in.json' and 'sap.tourist.in.json' files.

**Comment by hkhpub** [comment]
Thank you for reply.

I understand the structure of 'sap.guide.in.json' file and I have no problem with development.

What I am confused about is, for the unlabed test data set that will be released,
if it contains 'label.json' file, so that I can convert those to test instances like 'sap.guide.in.json'

If the test data set only contains 'log.json' file, than I should proceed the SLU task first to make test instances for the SAP task.

I'm not sure which one is the case.

**Comment by seokhwankim** [comment]
In the evaluation phase, only 'sap.guide.in.json' or 'sap.tourist.in.json' will be provided, which means that you don't need to convert the file formats in the evaluation phase.
And please note that each task will be evaluated with its own test dataset that is not overlapped with the ones for other tasks.

**Comment by hkhpub** [comment]
Thank you very much.

**Comment by seokhwankim** [comment]
You're welcome!
